/**
 * Presets de render por canal y plantillas de contenido de Vende Todo.
 *
 * Un RenderPreset define CÓMO se materializa una pieza (ratio, duración,
 * ritmo, CTA); un ContentTemplate define QUÉ cuenta (guion de escenas).
 * Storyboard = plantilla × preset × assets del inmueble.
 */

import type { ContentTemplate, RenderPreset } from "@/types/media";

export const RENDER_PRESETS: RenderPreset[] = [
  {
    id: "pr-whatsapp",
    name: "WhatsApp directo",
    channel: "whatsapp",
    ratio: "16:9",
    targetDurationSec: 35,
    maxDurationSec: 50,
    pace: "calmado",
    suggestedCopy: "Te comparto en 30 segundos la propiedad de la que hablamos — dime qué te parece y organizamos visita.",
    cta: "Responde a este mensaje y la vemos juntos",
    visualPriorities: ["salon", "cocina", "terraza", "exterior"],
    musicHint: "Piano cálido, volumen bajo (voz posible encima)",
  },
  {
    id: "pr-reels",
    name: "Instagram Reels",
    channel: "reels",
    ratio: "9:16",
    targetDurationSec: 22,
    maxDurationSec: 30,
    pace: "dinamico",
    suggestedCopy: "Así se vive en {location} ✨ Ref. {ref} · {price}",
    cta: "Link en bio · Escríbenos por DM",
    visualPriorities: ["vistas", "terraza", "salon", "cocina"],
    musicHint: "Tendencia actual con drop a los 3s",
  },
  {
    id: "pr-tiktok",
    name: "TikTok",
    channel: "tiktok",
    ratio: "9:16",
    targetDurationSec: 18,
    maxDurationSec: 25,
    pace: "rapido",
    suggestedCopy: "POV: encuentras piso en {location} por {price} 🏠",
    cta: "Sígue­nos para más pisos así en Oviedo",
    visualPriorities: ["vistas", "terraza", "detalle", "salon"],
    musicHint: "Sonido viral de la semana, cortes al ritmo",
  },
  {
    id: "pr-shorts",
    name: "YouTube Shorts",
    channel: "shorts",
    ratio: "9:16",
    targetDurationSec: 28,
    maxDurationSec: 45,
    pace: "dinamico",
    suggestedCopy: "Tour exprés: {ref} en {location} · {price}",
    cta: "Vídeo completo en el canal · enlace en descripción",
    visualPriorities: ["exterior", "salon", "cocina", "terraza"],
    musicHint: "Instrumental enérgico sin copyright",
  },
  {
    id: "pr-youtube",
    name: "YouTube tour completo",
    channel: "youtube",
    ratio: "16:9",
    targetDurationSec: 75,
    maxDurationSec: 120,
    pace: "calmado",
    suggestedCopy: "Tour completo por {ref}: {title}. Todos los datos en la descripción.",
    cta: "Agenda tu visita — teléfono en pantalla",
    visualPriorities: ["exterior", "portal", "salon", "cocina", "dormitorio", "terraza"],
    musicHint: "Ambiente elegante, tipo lounge suave",
  },
  {
    id: "pr-web",
    name: "Portal web / anuncios",
    channel: "web",
    ratio: "16:9",
    targetDurationSec: 45,
    maxDurationSec: 60,
    pace: "calmado",
    suggestedCopy: "Vídeo de ficha para portales inmobiliarios.",
    cta: "Solicita más información",
    visualPriorities: ["exterior", "salon", "cocina", "dormitorio", "bano"],
    musicHint: "Neutra corporativa cálida",
  },
  {
    id: "pr-cliente",
    name: "Ficha para cliente",
    channel: "client-portal",
    ratio: "4:5",
    targetDurationSec: 30,
    maxDurationSec: 40,
    pace: "calmado",
    suggestedCopy: "Pieza personal: “{firstName}, esta es la que te contaba…” — se adjunta a su portal privado.",
    cta: "Pide visita desde tu portal",
    visualPriorities: ["salon", "terraza", "cocina", "vistas"],
    musicHint: "Piano mínimo, protagonismo a los espacios",
  },
  {
    id: "pr-propietario",
    name: "Envío a propietario",
    channel: "owner-portal",
    ratio: "16:9",
    targetDurationSec: 40,
    maxDurationSec: 60,
    pace: "calmado",
    suggestedCopy: "Así estamos presentando tu inmueble esta semana. Métricas completas en tu portal.",
    cta: "Consulta la actividad en tu portal privado",
    visualPriorities: ["exterior", "salon", "cocina", "plano"],
    musicHint: "Sobria, transmite trabajo profesional",
  },
];

export const CONTENT_TEMPLATES: ContentTemplate[] = [
  {
    id: "tp-venta",
    name: "Vídeo de venta",
    goal: "venta",
    description: "Recorrido clásico que enamora: fachada, espacios de vida y remate en el punto fuerte.",
    tone: "Aspiracional sereno",
    sceneBlueprint: [
      { role: "gancho", roomHints: ["vistas", "terraza", "salon"], textHint: "Tu próxima casa en {location}" },
      { role: "espacio", roomHints: ["exterior", "portal"] },
      { role: "espacio", roomHints: ["salon"] },
      { role: "espacio", roomHints: ["cocina"] },
      { role: "espacio", roomHints: ["dormitorio"] },
      { role: "detalle", roomHints: ["terraza", "vistas", "detalle"] },
      { role: "datos", roomHints: ["plano"], textHint: "{ref} · {price}" },
      { role: "cta", roomHints: ["exterior", "salon"], textHint: "Visítala esta semana" },
    ],
    recommendedPresetIds: ["pr-web", "pr-youtube", "pr-whatsapp"],
  },
  {
    id: "tp-alquiler",
    name: "Vídeo de alquiler",
    goal: "alquiler",
    description: "Ritmo ágil centrado en cómo se vive el piso: listo para entrar, zonas útiles, entorno.",
    tone: "Cercano y práctico",
    sceneBlueprint: [
      { role: "gancho", roomHints: ["salon", "cocina"], textHint: "Listo para entrar en {location}" },
      { role: "espacio", roomHints: ["salon"] },
      { role: "espacio", roomHints: ["cocina"] },
      { role: "espacio", roomHints: ["dormitorio"] },
      { role: "espacio", roomHints: ["bano"] },
      { role: "datos", roomHints: ["plano", "detalle"], textHint: "{price} · disponible ya" },
      { role: "cta", roomHints: ["exterior"], textHint: "Escríbenos y la ves mañana" },
    ],
    recommendedPresetIds: ["pr-whatsapp", "pr-reels", "pr-web"],
  },
  {
    id: "tp-inversion",
    name: "Vídeo inversión",
    goal: "inversion",
    description: "Habla en números: precio/m², rentabilidad, demanda de la zona. Para inversores.",
    tone: "Directo, datos delante",
    sceneBlueprint: [
      { role: "gancho", roomHints: ["exterior", "plano"], textHint: "Oportunidad en {location}" },
      { role: "datos", roomHints: ["plano"], textHint: "{price} · alta demanda de alquiler" },
      { role: "espacio", roomHints: ["salon", "cocina"] },
      { role: "espacio", roomHints: ["dormitorio", "bano"] },
      { role: "datos", roomHints: ["detalle"], textHint: "Rentabilidad estimada en pantalla" },
      { role: "cta", roomHints: ["exterior"], textHint: "Pide el dossier de inversión" },
    ],
    recommendedPresetIds: ["pr-whatsapp", "pr-web"],
  },
  {
    id: "tp-premium",
    name: "Inmueble premium",
    goal: "premium",
    description: "Piezas largas y contemplativas: pocos cortes, mucho aire, detalle y materiales.",
    tone: "Editorial de lujo",
    sceneBlueprint: [
      { role: "gancho", roomHints: ["vistas", "exterior"], textHint: "{title}" },
      { role: "espacio", roomHints: ["portal", "exterior"] },
      { role: "espacio", roomHints: ["salon"] },
      { role: "detalle", roomHints: ["detalle", "cocina"] },
      { role: "espacio", roomHints: ["dormitorio"] },
      { role: "detalle", roomHints: ["terraza", "vistas"] },
      { role: "cta", roomHints: ["exterior"], textHint: "Visitas privadas con cita" },
    ],
    recommendedPresetIds: ["pr-youtube", "pr-cliente"],
  },
  {
    id: "tp-captacion",
    name: "Captación rápida",
    goal: "captacion",
    description: "Teaser de 15s para parar el scroll: 3 mejores planos, precio y CTA. Volumen y alcance.",
    tone: "Impacto inmediato",
    sceneBlueprint: [
      { role: "gancho", roomHints: ["vistas", "terraza", "salon"], textHint: "{price} en {location}" },
      { role: "espacio", roomHints: ["salon", "cocina"] },
      { role: "detalle", roomHints: ["terraza", "detalle"] },
      { role: "cta", roomHints: ["exterior"], textHint: "DM «INFO» y te lo enviamos" },
    ],
    recommendedPresetIds: ["pr-tiktok", "pr-reels"],
  },
  {
    id: "tp-propietario",
    name: "Actualización a propietario",
    goal: "propietario",
    description: "Resumen visual del trabajo hecho: cómo se presenta su inmueble y qué se ha movido.",
    tone: "Profesional, transparente",
    sceneBlueprint: [
      { role: "gancho", roomHints: ["exterior"], textHint: "Así presentamos tu inmueble" },
      { role: "espacio", roomHints: ["salon", "cocina"] },
      { role: "datos", roomHints: ["plano"], textHint: "Métricas de la semana en tu portal" },
      { role: "cta", roomHints: ["detalle"], textHint: "Entra a tu portal para el detalle" },
    ],
    recommendedPresetIds: ["pr-propietario"],
  },
  {
    id: "tp-resumen",
    name: "Resumen de marketing",
    goal: "resumen-marketing",
    description: "Pieza interna/comercial: recopila lo publicado y resultados para reuniones o informes.",
    tone: "Ejecutivo",
    sceneBlueprint: [
      { role: "gancho", roomHints: ["exterior"], textHint: "{ref} — resumen de campaña" },
      { role: "datos", roomHints: ["plano", "detalle"], textHint: "Alcance y leads en pantalla" },
      { role: "espacio", roomHints: ["salon"] },
      { role: "cta", roomHints: ["detalle"], textHint: "Siguiente acción propuesta" },
    ],
    recommendedPresetIds: ["pr-propietario", "pr-web"],
  },
];

export function getPreset(id: string): RenderPreset | null {
  return RENDER_PRESETS.find((p) => p.id === id) ?? null;
}

export function getTemplate(id: string): ContentTemplate | null {
  return CONTENT_TEMPLATES.find((t) => t.id === id) ?? null;
}
